# Generated by Django 3.1.3 on 2020-11-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_logs', '0002_auto_20201117_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='asctime',
        ),
    ]
